### ISSUE TITLE
Test case 15 failed

### ISSUE THREAD

**Issue by renetta96** [getsentry/perl-raven#35] opened 2020-08-30 15:22 UTC
I got this when trying `cpanm Sentry::Raven`:

```
t/11-generic-event.t ...... ok
t/12-specialized-event.t .. ok
t/13-service-call.t ....... ok
t/14-does-not-die.t ....... ok

    #   Failed test at t/15-error-handler.t line 58.
    #          got: '8'
    #     expected: '7'

    #   Failed test at t/15-error-handler.t line 60.
    #          got: 'Sentry::Raven::__ANON__'
    #     expected: 'main::c'

    #   Failed test at t/15-error-handler.t line 61.
    #          got: 'Sentry::Raven'
    #     expected: 'main'

    #   Failed test at t/15-error-handler.t line 62.
    #          got: '/home/wqmisc/.cpanm/work/1598799198.18017/Sentry-Raven-1.13/blib/lib/Sentry/Raven.pm'
    #     expected: 't/15-error-handler.t'

    #   Failed test at t/15-error-handler.t line 63.
    #          got: 'Raven.pm'
    #     expected: '15-error-handler.t'

    #   Failed test at t/15-error-handler.t line 64.
    #          got: '239'
    #     expected: '34'
    # Looks like you failed 6 tests of 6.

#   Failed test 'stacktrace'
#   at t/15-error-handler.t line 65.
# Looks like you failed 1 test of 5.
```

Perl version is 5.16.2

**Comment by querry43** [comment] 2020-10-12 03:52
Looking into this now.  My guess is older perl stack traces look a little different...

**Comment by querry43** [comment] 2020-10-12 04:30
I'm not sure what is different in your case.  Perhaps something is different about your perl build or environment.  I cannot reproduce this, but I can make the tests more general which should allow you to get farther.  This will be in version 1.14 which is going out shortly.

**Closed by querry43** 2020-10-12 04:30 UTC
